name: Update README.md

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
  schedule:
    - cron: "0 0 */2 * *"
env:
  YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16'
    - run: npm install
    - run: npm run update-readme
    - run: |
        git config user.name garu2
        git config user.email elgafo.nakama@gmail.com
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update README with latest info"
        git push origin
